### ISSUE TITLE
Jan 18th 2022 Currency Ref Data Meeting Minutes

### ISSUE THREAD

**Issue by agitana** [finos/curref-data#6]
# Currency Reference Data Meeting
[Currency Reference data overview, roadmap and background](https://github.com/finos/secref-data#currency-reference-data)

## Date
20220118 - 10am ET / 3pm GMT

## Untracked attendees
- n/a

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- **Housekeeping** (FINOS & LF)
    - [x] Update on new "project" status (see [project proposal issue](https://github.com/finos/community/issues/136))
    - [x] **Community Specification License overview and [enrollment](https://github.com/finos/curref-data/blob/master/governance-documents/..Getting%20Started.md#best-practices)** - _FINOS to share instructions to enroll_
    - [x] Decision on whether to close the [open issues in the secref-data repository](https://github.com/finos/secref-data/labels/Currency%20Reference%20Data) or migrate them into the [curref-data repository](https://github.com/finos/curref-data/) -_proposal to migrate issues_
    - [x] Re-assess meeting cadence - _agreement to move meetings to 3rd Tuesday of the month_
- [x] Approve past meeting minutes: 
    - [x] [November 9th meeting minutes](https://github.com/finos/secref-data/issues/77) 
    - [x] [November 23rd meeting minutes](https://github.com/finos/secref-data/issues/78): _move outstanding items to next meeting agenda_:
        - Data storage and changes to existing datasets (see https://github.com/finos/secref-data/issues/77#issuecomment-964262983) (Sailesh Pandey)
        - Review of a proposal for automated checks on new/changed list entries (Elaine Fraser)
        - Discuss what the ‘next category’ of list entries should be (Elaine Fraser)
        - Cryptocurrencies (Elaine Fraser)
- [x] FINOS All Community Call, February 2nd: projects welcome to propose project updates at https://github.com/finos/community/issues/152
- [x] AOB, Q&A & Adjourn (5mins)

## Action Items
- [x] FINOS to update currency reference data meeting cadence from fortnightly to monthly
- [x] FINOS to transfer curref-data related issues to curref-data repository from secref-data repository 
- [x] FINOS to move outstanding agenda items from November 23rd meeting into February 15th meeting agenda
- [x] FINOS to share instructions on Community Specification License enrollment with currency reference data mailing list

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf27815a7807f13f1d0974a973196cb4c)
- Meeting Number: 127 819 0322
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 127 819 0322
- Password: VXcd2eQgh82
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by Jourik-de-Lange** [comment]
Im in

**Comment by ElaineFraser** [comment]
hi

**Comment by Vijayesh-Chandel** [comment]
Hello

**Comment by agitana** [comment]
Aitana Myohl / FINOS

**Comment by iansloyan** [comment]
Ian Sloyan / ISDA

**Comment by MA-GQ** [comment]
Miguel Quesada / Canonical

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by saileshpandey** [comment]
Sailesh / Nomura

**Comment by jgavronsky** [comment]
Jane @ FINOS here
